###############################################################
# Eclipse Tractus-X - Industry Core Hub
#
# Copyright (c) 2026 LKS Next
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

"""Create the application schema for a fresh database."""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS cache')
    op.execute(sa.text('SET search_path TO public'))
    op.create_table('known_connectors',
    sa.Column('bpnl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connectors', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bpnl'),
    schema='cache'
    )
    op.create_index(op.f('ix_known_connectors_bpnl'), 'known_connectors', ['bpnl'], unique=False, schema='cache')
    op.create_index(op.f('ix_known_connectors_expires_at'), 'known_connectors', ['expires_at'], unique=False, schema='cache')
    op.create_table('known_dtrs',
    sa.Column('bpnl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edc_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policies', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bpnl', 'asset_id'),
    schema='cache'
    )
    op.create_index(op.f('ix_known_dtrs_bpnl'), 'known_dtrs', ['bpnl'], unique=False, schema='cache')
    op.create_index(op.f('ix_known_dtrs_expires_at'), 'known_dtrs', ['expires_at'], unique=False, schema='cache')
    op.create_table('business_partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bpnl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_partner_bpnl'), 'business_partner', ['bpnl'], unique=True)
    op.create_index(op.f('ix_business_partner_name'), 'business_partner', ['name'], unique=True)
    op.create_table('ccm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bpnl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issuer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('trust_level', sa.Enum('none', 'low', 'high', 'trusted', name='trust_level'), nullable=False),
    sa.Column('certificate_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('area_of_application', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('certificate_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validator_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issuer_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploader_bpnl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('edc_asset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccm_bpnl'), 'ccm', ['bpnl'], unique=False)
    op.create_index('ix_ccm_bpnl_certificate_type', 'ccm', ['bpnl', 'certificate_type'], unique=False)
    op.create_index(op.f('ix_ccm_certificate_name'), 'ccm', ['certificate_name'], unique=False)
    op.create_index(op.f('ix_ccm_certificate_type'), 'ccm', ['certificate_type'], unique=False)
    op.create_index(op.f('ix_ccm_edc_asset_id'), 'ccm', ['edc_asset_id'], unique=False)
    op.create_index(op.f('ix_ccm_issuer'), 'ccm', ['issuer'], unique=False)
    op.create_index(op.f('ix_ccm_issuer_bpn'), 'ccm', ['issuer_bpn'], unique=False)
    op.create_index(op.f('ix_ccm_registration_number'), 'ccm', ['registration_number'], unique=False)
    op.create_index(op.f('ix_ccm_trust_level'), 'ccm', ['trust_level'], unique=False)
    op.create_index(op.f('ix_ccm_uploader_bpnl'), 'ccm', ['uploader_bpnl'], unique=False)
    op.create_index(op.f('ix_ccm_valid_from'), 'ccm', ['valid_from'], unique=False)
    op.create_index(op.f('ix_ccm_valid_until'), 'ccm', ['valid_until'], unique=False)
    op.create_index(op.f('ix_ccm_validator_bpn'), 'ccm', ['validator_bpn'], unique=False)
    op.create_table('ccm_outbound_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certified_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_bpns', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('governance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Found', 'NotFound', 'Failed', name='outbound_request_status'), nullable=False),
    sa.Column('notification_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccm_outbound_request_certificate_type'), 'ccm_outbound_request', ['certificate_type'], unique=False)
    op.create_index(op.f('ix_ccm_outbound_request_certified_bpn'), 'ccm_outbound_request', ['certified_bpn'], unique=False)
    op.create_index(op.f('ix_ccm_outbound_request_document_id'), 'ccm_outbound_request', ['document_id'], unique=False)
    op.create_index(op.f('ix_ccm_outbound_request_notification_id'), 'ccm_outbound_request', ['notification_id'], unique=False)
    op.create_index(op.f('ix_ccm_outbound_request_provider_bpn'), 'ccm_outbound_request', ['provider_bpn'], unique=False)
    op.create_index('ix_ccm_outbound_request_provider_certified', 'ccm_outbound_request', ['provider_bpn', 'certified_bpn', 'certificate_type'], unique=False)
    op.create_index(op.f('ix_ccm_outbound_request_sender_bpn'), 'ccm_outbound_request', ['sender_bpn'], unique=False)
    op.create_index(op.f('ix_ccm_outbound_request_status'), 'ccm_outbound_request', ['status'], unique=False)
    op.create_table('ccm_received',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certified_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificate_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issuer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issuer_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('trust_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('area_of_application', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploader_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('doc', sa.LargeBinary(), nullable=True),
    sa.Column('local_status', sa.Enum('Pending', 'Received', 'Accepted', 'Rejected', name='received_certificate_status'), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notification_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'provider_bpn', name='uq_ccm_received_doc_provider')
    )
    op.create_index(op.f('ix_ccm_received_certificate_type'), 'ccm_received', ['certificate_type'], unique=False)
    op.create_index(op.f('ix_ccm_received_certified_bpn'), 'ccm_received', ['certified_bpn'], unique=False)
    op.create_index(op.f('ix_ccm_received_document_id'), 'ccm_received', ['document_id'], unique=False)
    op.create_index(op.f('ix_ccm_received_local_status'), 'ccm_received', ['local_status'], unique=False)
    op.create_index(op.f('ix_ccm_received_notification_message_id'), 'ccm_received', ['notification_message_id'], unique=False)
    op.create_index(op.f('ix_ccm_received_provider_bpn'), 'ccm_received', ['provider_bpn'], unique=False)
    op.create_table('legal_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bpnl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_entity_bpnl'), 'legal_entity', ['bpnl'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('sender_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('receiver_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sa.Enum('incoming', 'outgoing', name='notification_direction'), nullable=False),
    sa.Column('status', sa.Enum('received', 'read', 'pending', 'sent', 'failed', name='notification_status'), nullable=False),
    sa.Column('use_case', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_direction'), 'notifications', ['direction'], unique=False)
    op.create_index(op.f('ix_notifications_location'), 'notifications', ['location'], unique=False)
    op.create_index(op.f('ix_notifications_message_id'), 'notifications', ['message_id'], unique=True)
    op.create_index(op.f('ix_notifications_receiver_bpn'), 'notifications', ['receiver_bpn'], unique=False)
    op.create_index(op.f('ix_notifications_sender_bpn'), 'notifications', ['sender_bpn'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_table('pcf_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.Enum('outgoing', 'incoming', name='pcf_exchange_direction'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'updated', 'rejected', 'failed', 'cancelled', name='pcf_exchange_status'), nullable=False),
    sa.Column('type', sa.Enum('request', 'response', name='pcf_exchange_type'), nullable=False),
    sa.Column('requesting_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('responding_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manufacturer_part_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_part_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pcf_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'type', name='uk_pcf_exchanges_request_id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_pcf_exchanges_correlation_id'), 'pcf_exchanges', ['correlation_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_pcf_exchanges_customer_part_id'), 'pcf_exchanges', ['customer_part_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_pcf_exchanges_direction'), 'pcf_exchanges', ['direction'], unique=False, schema='public')
    op.create_index(op.f('ix_public_pcf_exchanges_manufacturer_part_id'), 'pcf_exchanges', ['manufacturer_part_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_pcf_exchanges_request_id'), 'pcf_exchanges', ['request_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_pcf_exchanges_requesting_bpn'), 'pcf_exchanges', ['requesting_bpn'], unique=False, schema='public')
    op.create_index(op.f('ix_public_pcf_exchanges_responding_bpn'), 'pcf_exchanges', ['responding_bpn'], unique=False, schema='public')
    op.create_index(op.f('ix_public_pcf_exchanges_status'), 'pcf_exchanges', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_pcf_exchanges_type'), 'pcf_exchanges', ['type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_pcf_exchanges_version'), 'pcf_exchanges', ['version'], unique=False, schema='public')
    op.create_table('pcf_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_manufacturer_part_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('list_sub_manufacturer_part_id', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_pcf_relationships_main_manufacturer_part_id'), 'pcf_relationships', ['main_manufacturer_part_id'], unique=False, schema='public')
    op.create_table('twin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_id', sa.Uuid(), nullable=False),
    sa.Column('aas_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('asset_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('additional_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aas_id'),
    sa.UniqueConstraint('global_id')
    )
    op.create_index(op.f('ix_twin_created_date'), 'twin', ['created_date'], unique=False)
    op.create_index(op.f('ix_twin_modified_date'), 'twin', ['modified_date'], unique=False)
    op.create_table('catalog_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_part_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legal_entity_id', sa.Integer(), nullable=False),
    sa.Column('twin_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bpns', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('width', sa.JSON(), nullable=True),
    sa.Column('height', sa.JSON(), nullable=True),
    sa.Column('length', sa.JSON(), nullable=True),
    sa.Column('weight', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entity.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legal_entity_id', 'manufacturer_part_id', name='uk_catalog_part_legal_entity_id_manufacturer_part_id'),
    sa.UniqueConstraint('twin_id')
    )
    op.create_index(op.f('ix_catalog_part_legal_entity_id'), 'catalog_part', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_catalog_part_manufacturer_part_id'), 'catalog_part', ['manufacturer_part_id'], unique=False)
    op.create_table('ccm_inbound_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consumer_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certified_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('certificate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location_bpns', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NotFound', 'Registered', 'Available', 'Pushed', name='inbound_request_status'), nullable=False),
    sa.Column('notification_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('consumer_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['ccm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccm_inbound_request_certificate_id'), 'ccm_inbound_request', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_ccm_inbound_request_certificate_type'), 'ccm_inbound_request', ['certificate_type'], unique=False)
    op.create_index(op.f('ix_ccm_inbound_request_certified_bpn'), 'ccm_inbound_request', ['certified_bpn'], unique=False)
    op.create_index(op.f('ix_ccm_inbound_request_consumer_bpn'), 'ccm_inbound_request', ['consumer_bpn'], unique=False)
    op.create_index('ix_ccm_inbound_request_consumer_certified', 'ccm_inbound_request', ['consumer_bpn', 'certified_bpn', 'certificate_type'], unique=False)
    op.create_index(op.f('ix_ccm_inbound_request_notification_id'), 'ccm_inbound_request', ['notification_id'], unique=False)
    op.create_index(op.f('ix_ccm_inbound_request_status'), 'ccm_inbound_request', ['status'], unique=False)
    op.create_table('ccm_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ccm_id', sa.Integer(), nullable=False),
    sa.Column('site_bpn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area_of_application', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['ccm_id'], ['ccm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ccm_site_ccm_id'), 'ccm_site', ['ccm_id'], unique=False)
    op.create_index(op.f('ix_ccm_site_site_bpn'), 'ccm_site', ['site_bpn'], unique=False)
    op.create_table('certificate_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('consumer_bpnl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_shared_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Pending', 'Revoked', name='share_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['ccm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cert_share_certificate_id_consumer_bpnl', 'certificate_share', ['certificate_id', 'consumer_bpnl'], unique=False)
    op.create_index(op.f('ix_certificate_share_certificate_id'), 'certificate_share', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_certificate_share_consumer_bpnl'), 'certificate_share', ['consumer_bpnl'], unique=False)
    op.create_index(op.f('ix_certificate_share_status'), 'certificate_share', ['status'], unique=False)
    op.create_table('data_exchange_agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_partner_id'], ['business_partner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_partner_id', 'name', name='uk_data_exchange_agreement_name_business_partner_id')
    )
    op.create_index(op.f('ix_data_exchange_agreement_business_partner_id'), 'data_exchange_agreement', ['business_partner_id'], unique=False)
    op.create_index(op.f('ix_data_exchange_agreement_name'), 'data_exchange_agreement', ['name'], unique=False)
    op.create_table('enablement_service_stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_settings', sa.JSON(), nullable=True),
    sa.Column('legal_entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enablement_service_stack_legal_entity_id'), 'enablement_service_stack', ['legal_entity_id'], unique=False)
    op.create_index(op.f('ix_enablement_service_stack_name'), 'enablement_service_stack', ['name'], unique=True)
    op.create_table('twin_aspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submodel_id', sa.Uuid(), nullable=False),
    sa.Column('semantic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('twin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['twin_id'], ['twin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submodel_id'),
    sa.UniqueConstraint('twin_id', 'semantic_id', name='uk_twin_aspect_twin_id_semantic_id')
    )
    op.create_index(op.f('ix_twin_aspect_semantic_id'), 'twin_aspect', ['semantic_id'], unique=False)
    op.create_index(op.f('ix_twin_aspect_twin_id'), 'twin_aspect', ['twin_id'], unique=False)
    op.create_table('batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('catalog_part_id', sa.Integer(), nullable=False),
    sa.Column('twin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_part_id'], ['catalog_part.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_part_id', 'batch_id', name='uk_batch_catalog_part_id_batch_id'),
    sa.UniqueConstraint('twin_id')
    )
    op.create_index(op.f('ix_batch_batch_id'), 'batch', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_catalog_part_id'), 'batch', ['catalog_part_id'], unique=False)
    op.create_table('data_exchange_contract',
    sa.Column('data_exchange_agreement_id', sa.Integer(), nullable=False),
    sa.Column('semantic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edc_usage_policy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['data_exchange_agreement_id'], ['data_exchange_agreement.id'], ),
    sa.PrimaryKeyConstraint('data_exchange_agreement_id', 'semantic_id')
    )
    op.create_table('partner_catalog_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_partner_id', sa.Integer(), nullable=False),
    sa.Column('catalog_part_id', sa.Integer(), nullable=False),
    sa.Column('customer_part_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['business_partner_id'], ['business_partner.id'], ),
    sa.ForeignKeyConstraint(['catalog_part_id'], ['catalog_part.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_partner_id', 'catalog_part_id', name='uk_partner_catalog_part_business_partner_id_catalog_part_id')
    )
    op.create_index(op.f('ix_partner_catalog_part_business_partner_id'), 'partner_catalog_part', ['business_partner_id'], unique=False)
    op.create_index(op.f('ix_partner_catalog_part_catalog_part_id'), 'partner_catalog_part', ['catalog_part_id'], unique=False)
    op.create_index(op.f('ix_partner_catalog_part_customer_part_id'), 'partner_catalog_part', ['customer_part_id'], unique=False)
    op.create_table('twin_aspect_registration',
    sa.Column('twin_aspect_id', sa.Integer(), nullable=False),
    sa.Column('enablement_service_stack_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('registration_mode', sa.SmallInteger(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enablement_service_stack_id'], ['enablement_service_stack.id'], ),
    sa.ForeignKeyConstraint(['twin_aspect_id'], ['twin_aspect.id'], ),
    sa.PrimaryKeyConstraint('twin_aspect_id', 'enablement_service_stack_id')
    )
    op.create_index(op.f('ix_twin_aspect_registration_created_date'), 'twin_aspect_registration', ['created_date'], unique=False)
    op.create_index(op.f('ix_twin_aspect_registration_modified_date'), 'twin_aspect_registration', ['modified_date'], unique=False)
    op.create_index(op.f('ix_twin_aspect_registration_registration_mode'), 'twin_aspect_registration', ['registration_mode'], unique=False)
    op.create_index(op.f('ix_twin_aspect_registration_status'), 'twin_aspect_registration', ['status'], unique=False)
    op.create_table('twin_exchange',
    sa.Column('twin_id', sa.Integer(), nullable=False),
    sa.Column('data_exchange_agreement_id', sa.Integer(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['data_exchange_agreement_id'], ['data_exchange_agreement.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twin.id'], ),
    sa.PrimaryKeyConstraint('twin_id', 'data_exchange_agreement_id')
    )
    op.create_index(op.f('ix_twin_exchange_data_exchange_agreement_id'), 'twin_exchange', ['data_exchange_agreement_id'], unique=False)
    op.create_index(op.f('ix_twin_exchange_is_cancelled'), 'twin_exchange', ['is_cancelled'], unique=False)
    op.create_table('twin_registration',
    sa.Column('twin_id', sa.Integer(), nullable=False),
    sa.Column('enablement_service_stack_id', sa.Integer(), nullable=False),
    sa.Column('dtr_registered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enablement_service_stack_id'], ['enablement_service_stack.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twin.id'], ),
    sa.PrimaryKeyConstraint('twin_id', 'enablement_service_stack_id')
    )
    op.create_index(op.f('ix_twin_registration_dtr_registered'), 'twin_registration', ['dtr_registered'], unique=False)
    op.create_table('batch_business_partner',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('business_partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ),
    sa.ForeignKeyConstraint(['business_partner_id'], ['business_partner.id'], ),
    sa.PrimaryKeyConstraint('batch_id', 'business_partner_id')
    )
    op.create_table('jis_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_catalog_part_id', sa.Integer(), nullable=False),
    sa.Column('jis_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jis_call_date', sa.DateTime(), nullable=True),
    sa.Column('twin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_catalog_part_id'], ['partner_catalog_part.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jis_number', 'partner_catalog_part_id', name='uk_jis_part_partner_catalog_part_id_jis_number'),
    sa.UniqueConstraint('twin_id')
    )
    op.create_index(op.f('ix_jis_part_jis_call_date'), 'jis_part', ['jis_call_date'], unique=False)
    op.create_index(op.f('ix_jis_part_jis_number'), 'jis_part', ['jis_number'], unique=False)
    op.create_index(op.f('ix_jis_part_parent_order_number'), 'jis_part', ['parent_order_number'], unique=False)
    op.create_index(op.f('ix_jis_part_partner_catalog_part_id'), 'jis_part', ['partner_catalog_part_id'], unique=False)
    op.create_table('serialized_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_catalog_part_id', sa.Integer(), nullable=False),
    sa.Column('part_instance_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('van', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partner_catalog_part_id'], ['partner_catalog_part.id'], ),
    sa.ForeignKeyConstraint(['twin_id'], ['twin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_instance_id', 'partner_catalog_part_id', name='uk_serialized_part_partner_catalog_part_id_part_instance_id'),
    sa.UniqueConstraint('twin_id')
    )
    op.create_index(op.f('ix_serialized_part_part_instance_id'), 'serialized_part', ['part_instance_id'], unique=False)
    op.create_index(op.f('ix_serialized_part_partner_catalog_part_id'), 'serialized_part', ['partner_catalog_part_id'], unique=False)
    op.create_index(op.f('ix_serialized_part_van'), 'serialized_part', ['van'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_known_dtrs_expires_at'), table_name='known_dtrs', schema='cache')
    op.drop_index(op.f('ix_known_dtrs_bpnl'), table_name='known_dtrs', schema='cache')
    op.drop_table('known_dtrs', schema='cache')
    op.drop_index(op.f('ix_known_connectors_expires_at'), table_name='known_connectors', schema='cache')
    op.drop_index(op.f('ix_known_connectors_bpnl'), table_name='known_connectors', schema='cache')
    op.drop_table('known_connectors', schema='cache')
    op.drop_index(op.f('ix_serialized_part_van'), table_name='serialized_part')
    op.drop_index(op.f('ix_serialized_part_partner_catalog_part_id'), table_name='serialized_part')
    op.drop_index(op.f('ix_serialized_part_part_instance_id'), table_name='serialized_part')
    op.drop_table('serialized_part')
    op.drop_index(op.f('ix_jis_part_partner_catalog_part_id'), table_name='jis_part')
    op.drop_index(op.f('ix_jis_part_parent_order_number'), table_name='jis_part')
    op.drop_index(op.f('ix_jis_part_jis_number'), table_name='jis_part')
    op.drop_index(op.f('ix_jis_part_jis_call_date'), table_name='jis_part')
    op.drop_table('jis_part')
    op.drop_table('batch_business_partner')
    op.drop_index(op.f('ix_twin_registration_dtr_registered'), table_name='twin_registration')
    op.drop_table('twin_registration')
    op.drop_index(op.f('ix_twin_exchange_is_cancelled'), table_name='twin_exchange')
    op.drop_index(op.f('ix_twin_exchange_data_exchange_agreement_id'), table_name='twin_exchange')
    op.drop_table('twin_exchange')
    op.drop_index(op.f('ix_twin_aspect_registration_status'), table_name='twin_aspect_registration')
    op.drop_index(op.f('ix_twin_aspect_registration_registration_mode'), table_name='twin_aspect_registration')
    op.drop_index(op.f('ix_twin_aspect_registration_modified_date'), table_name='twin_aspect_registration')
    op.drop_index(op.f('ix_twin_aspect_registration_created_date'), table_name='twin_aspect_registration')
    op.drop_table('twin_aspect_registration')
    op.drop_index(op.f('ix_partner_catalog_part_customer_part_id'), table_name='partner_catalog_part')
    op.drop_index(op.f('ix_partner_catalog_part_catalog_part_id'), table_name='partner_catalog_part')
    op.drop_index(op.f('ix_partner_catalog_part_business_partner_id'), table_name='partner_catalog_part')
    op.drop_table('partner_catalog_part')
    op.drop_table('data_exchange_contract')
    op.drop_index(op.f('ix_batch_catalog_part_id'), table_name='batch')
    op.drop_index(op.f('ix_batch_batch_id'), table_name='batch')
    op.drop_table('batch')
    op.drop_index(op.f('ix_twin_aspect_twin_id'), table_name='twin_aspect')
    op.drop_index(op.f('ix_twin_aspect_semantic_id'), table_name='twin_aspect')
    op.drop_table('twin_aspect')
    op.drop_index(op.f('ix_enablement_service_stack_name'), table_name='enablement_service_stack')
    op.drop_index(op.f('ix_enablement_service_stack_legal_entity_id'), table_name='enablement_service_stack')
    op.drop_table('enablement_service_stack')
    op.drop_index(op.f('ix_data_exchange_agreement_name'), table_name='data_exchange_agreement')
    op.drop_index(op.f('ix_data_exchange_agreement_business_partner_id'), table_name='data_exchange_agreement')
    op.drop_table('data_exchange_agreement')
    op.drop_index(op.f('ix_certificate_share_status'), table_name='certificate_share')
    op.drop_index(op.f('ix_certificate_share_consumer_bpnl'), table_name='certificate_share')
    op.drop_index(op.f('ix_certificate_share_certificate_id'), table_name='certificate_share')
    op.drop_index('ix_cert_share_certificate_id_consumer_bpnl', table_name='certificate_share')
    op.drop_table('certificate_share')
    op.drop_index(op.f('ix_ccm_site_site_bpn'), table_name='ccm_site')
    op.drop_index(op.f('ix_ccm_site_ccm_id'), table_name='ccm_site')
    op.drop_table('ccm_site')
    op.drop_index(op.f('ix_ccm_inbound_request_status'), table_name='ccm_inbound_request')
    op.drop_index(op.f('ix_ccm_inbound_request_notification_id'), table_name='ccm_inbound_request')
    op.drop_index('ix_ccm_inbound_request_consumer_certified', table_name='ccm_inbound_request')
    op.drop_index(op.f('ix_ccm_inbound_request_consumer_bpn'), table_name='ccm_inbound_request')
    op.drop_index(op.f('ix_ccm_inbound_request_certified_bpn'), table_name='ccm_inbound_request')
    op.drop_index(op.f('ix_ccm_inbound_request_certificate_type'), table_name='ccm_inbound_request')
    op.drop_index(op.f('ix_ccm_inbound_request_certificate_id'), table_name='ccm_inbound_request')
    op.drop_table('ccm_inbound_request')
    op.drop_index(op.f('ix_catalog_part_manufacturer_part_id'), table_name='catalog_part')
    op.drop_index(op.f('ix_catalog_part_legal_entity_id'), table_name='catalog_part')
    op.drop_table('catalog_part')
    op.drop_index(op.f('ix_twin_modified_date'), table_name='twin')
    op.drop_index(op.f('ix_twin_created_date'), table_name='twin')
    op.drop_table('twin')
    op.drop_index(op.f('ix_public_pcf_relationships_main_manufacturer_part_id'), table_name='pcf_relationships', schema='public')
    op.drop_table('pcf_relationships', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_version'), table_name='pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_type'), table_name='pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_status'), table_name='pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_responding_bpn'), table_name='pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_requesting_bpn'), table_name='pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_request_id'), table_name='pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_manufacturer_part_id'), table_name='pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_direction'), table_name='pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_customer_part_id'), table_name='pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_public_pcf_exchanges_correlation_id'), table_name='pcf_exchanges', schema='public')
    op.drop_table('pcf_exchanges', schema='public')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sender_bpn'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_receiver_bpn'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_message_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_location'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_direction'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_legal_entity_bpnl'), table_name='legal_entity')
    op.drop_table('legal_entity')
    op.drop_index(op.f('ix_ccm_received_provider_bpn'), table_name='ccm_received')
    op.drop_index(op.f('ix_ccm_received_notification_message_id'), table_name='ccm_received')
    op.drop_index(op.f('ix_ccm_received_local_status'), table_name='ccm_received')
    op.drop_index(op.f('ix_ccm_received_document_id'), table_name='ccm_received')
    op.drop_index(op.f('ix_ccm_received_certified_bpn'), table_name='ccm_received')
    op.drop_index(op.f('ix_ccm_received_certificate_type'), table_name='ccm_received')
    op.drop_table('ccm_received')
    op.drop_index(op.f('ix_ccm_outbound_request_status'), table_name='ccm_outbound_request')
    op.drop_index(op.f('ix_ccm_outbound_request_sender_bpn'), table_name='ccm_outbound_request')
    op.drop_index('ix_ccm_outbound_request_provider_certified', table_name='ccm_outbound_request')
    op.drop_index(op.f('ix_ccm_outbound_request_provider_bpn'), table_name='ccm_outbound_request')
    op.drop_index(op.f('ix_ccm_outbound_request_notification_id'), table_name='ccm_outbound_request')
    op.drop_index(op.f('ix_ccm_outbound_request_document_id'), table_name='ccm_outbound_request')
    op.drop_index(op.f('ix_ccm_outbound_request_certified_bpn'), table_name='ccm_outbound_request')
    op.drop_index(op.f('ix_ccm_outbound_request_certificate_type'), table_name='ccm_outbound_request')
    op.drop_table('ccm_outbound_request')
    op.drop_index(op.f('ix_ccm_validator_bpn'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_valid_until'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_valid_from'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_uploader_bpnl'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_trust_level'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_registration_number'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_issuer_bpn'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_issuer'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_edc_asset_id'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_certificate_type'), table_name='ccm')
    op.drop_index(op.f('ix_ccm_certificate_name'), table_name='ccm')
    op.drop_index('ix_ccm_bpnl_certificate_type', table_name='ccm')
    op.drop_index(op.f('ix_ccm_bpnl'), table_name='ccm')
    op.drop_table('ccm')
    op.drop_index(op.f('ix_business_partner_name'), table_name='business_partner')
    op.drop_index(op.f('ix_business_partner_bpnl'), table_name='business_partner')
    op.drop_table('business_partner')
    for enum_name in (
        'trust_level',
        'outbound_request_status',
        'received_certificate_status',
        'notification_direction',
        'notification_status',
        'pcf_exchange_direction',
        'pcf_exchange_status',
        'pcf_exchange_type',
        'inbound_request_status',
        'share_status',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))
    op.execute('DROP SCHEMA IF EXISTS cache CASCADE')
    # ### end Alembic commands ###