#################################################################################
# Eclipse Tractus-X - Industry Core Hub Backend
#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the
# License for the specific language govern in permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#################################################################################

openapi: 3.0.1
info:
  title: ICHUB-Backend
  description: The ICHUB-Backend OpenApi 
  version: 0.0.1

servers:
  - url: http://ichub-backend.tx.test/
    description: Backend

paths:
  /shells:
    get:
      summary: Returns a list of all the products that user can see.
      responses:
        "200": # status code
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductsMetadata'
  /shell/{id}:
    get:
      summary: Returns a product base an id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsMetadata'
    delete:
      summary: Delete a product base an id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsMetadata'
  /shell:
    post:
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductsAllInfo'
      responses:
        "200": # status code
          description: A JSON array of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsMetadata'

components:
  schemas:
    batch_overview:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        batch_id:
          type: string
        customer_part_ids:
          type: json
    batch_overview_partner_parts:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        batch_id:
          type: string
        customer_part_id:
          type: string
        external_subject_id:
          type: string
        business_partner:
          type: string
    batch_shared_twins_aspects:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        batch_id:
          type: string
        customer_part_ids:
          type: json
        catenax_id:
          type: uuid
        semantic_id:
          type: string
        business_partner_name:
          type: string
        data_exchange_agreement:
          type: string
        edc_usage_policy_id:
          type: string
        enablement_service_stack:
          type: string
        dtr_registered:
          type: boolean
        status:
          type: smallint
        registration_mode:
          type: smallint
    batch_twins_aspects:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        batch_id:
          type: string
        customer_part_ids:
          type: json
        catenax_id:
          type: uuid
        semantic_id:
          type: string
        dtr_registered:
          type: boolean
        name:
          type: string
        status:
          type: smallint
        registration_mode:
          type: smallint
    catalog_part_overview:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_ids:
          type: json
    catalog_part_overview_with_partners:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_id:
          type: string
        external_subject_id:
          type: string
        business_partner:
          type: string
    catalog_part_shared_twins_aspects:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_ids:
          type: json
        catenax_id:
          type: uuid
        semantic_id:
          type: string
        business_partner_name:
          type: string
        data_exchange_agreement:
          type: string
        edc_usage_policy_id:
          type: string
        enablement_service_stack:
          type: string
        dtr_registered:
          type: boolean
        status:
          type: smallint
        registration_mode:
          type: smallint
    catalog_part_twins_aspects:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_ids:
          type: json
        catenax_id:
          type: uuid
        semantic_id:
          type: string
        dtr_registered:
          type: boolean
        name:
          type: string
        status:
          type: smallint
        registration_mode:
          type: smallint
    data_exchange_agreements:
      type: object
      properties:
        business_partner:
          type: string
        data_exchange_agreements:
          type: string
        semantic_id:
          type: string
        edc_usage_policy_id:
          type: string
    jis_part_overview:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_id:
          type: string
        jis_number:
          type: string
        parent_order_number:
          type: string
        jis_call_date:
          type: timestamp
        external_subject_id:
          type: string
        business_partner:
          type: string
    jis_part_shared_twins_aspects:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_id:
          type: string
        jis_number:
          type: string
        parent_order_number:
          type: string
        jis_call_date:
          type: timestamp
        external_subject_id:
          type: string
        business_partner:
          type: string
        catenax_id:
          type: uuid
        semantic_id:
          type: string
        data_exchange_agreement:
          type: string
        edc_usage_policy_id:
          type: string
        name:
          type: string
        dtr_registered:
          type: boolean
        status:
          type: smallint
        registration_mode:
          type: smallint
    jis_part_twins_aspects:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_id:
          type: string
        jis_number:
          type: string
        parent_order_number:
          type: string
        jis_call_date:
          type: timestamp
        external_subject_id:
          type: string
        business_partner:
          type: string
        catenax_id:
          type: uuid
        semantic_id:
          type: string
        name:
          type: string
        dtr_registered:
          type: boolean
        status:
          type: smallint
        registration_mode:
          type: smallint
    serialized_part_overview:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_id:
          type: string
        part_instance_id:
          type: string
        van:
          type: string
        external_subject_id:
          type: string
        business_partner:
          type: string
    serialized_part_shared_twins_aspects:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_id:
          type: string
        part_instance_id:
          type: string
        van:
          type: string
        external_subject_id:
          type: string
        business_partner:
          type: string
        catenax_id:
          type: uuid
        semantic_id:
          type: string
        data_exchange_agreement:
          type: string
        edc_usage_policy_id:
          type: string
        name:
          type: string
        dtr_registered:
          type: boolean
        status:
          type: smallint
        registration_mode:
          type: smallint
    serialized_part_twins_aspects:
      type: object
      properties:
        manufacturer_id:
          type: string
        manufacturer_part_id:
          type: string
        customer_part_id:
          type: string
        part_instance_id:
          type: string
        van:
          type: string
        external_subject_id:
          type: string
        business_partner:
          type: string
        catenax_id:
          type: uuid
        semantic_id:
          type: string
        name:
          type: string
        dtr_registered:
          type: boolean
        status:
          type: smallint
        registration_mode:
          type: smallint
