###############################################################
# Eclipse Tractus-X - Industry Core Hub
#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################
---
## For being used in the Integration ArgoCD test environment from the Catena-X Association

postgresql:
  auth:
    ## Root password override
    password: <path:industry-core-hub/data/db#rootPass>
    ## Industry Core User Password
    ichubPassword: <path:industry-core-hub/data/db#ichubPass>
    
# -- pgAdmin4 configuration
pgadmin4:
  enabled: true
  env:
    email: <path:industry-core-hub/data/pgadmin#email>
    password: <path:industry-core-hub/data/pgadmin#password>
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: pgadmin-ichub.int.catena-x.net
        paths:
          - path: /
            pathType: Prefix
    tls:
       - secretName: "pgadmin-ichub.int.catena-x.net-tls"
         hosts:
           - "pgadmin-ichub.int.catena-x.net" 
frontend: 
  ingress:
      enabled: true
      className: "nginx"
      ## Optional annotations when using the nginx ingress class
      annotations:
       cert-manager.io/cluster-issuer: letsencrypt-prod
      #   nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      #   nginx.ingress.kubernetes.io/use-regex: "true"
      #   nginx.ingress.kubernetes.io/enable-cors: "true"
      #   # -- Provide CORS allowed origin.
      #   nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.example.org"
      # -- Ingress TLS configuration
      tls:
       - secretName: "frontend-ichub.int.catena-x.net-tls"
         hosts:
           - "frontend-ichub.int.catena-x.net" 
        # # -- Provide tls secret.
        # - secretName: ""
        #   # -- Provide host for tls secret.
        #   hosts:
        #     - ""
      hosts:
        - host: "frontend-ichub.int.catena-x.net"
          paths:
            - path: /
              pathType: ImplementationSpecific
              backend:
                service: "frontend"
                port: 8080
backend:
  # -- Persistance configuration for the backend
  persistence:
    # -- Create a PVC to persist storage (if disabled, data and logs will not be persisted)
    enabled: true
    data:
      # -- Enable data persistence
      enabled: true
      # -- Storage size for data
      size: 1Gi
      # -- Access mode for data volume
      accessMode: ReadWriteOnce
      # -- Storage class for data volume
      storageClass: "default"
    logs:
      # -- Enable logs persistence
      enabled: true
      # -- Storage size for logs
      size: 1Gi
      # -- Access mode for logs volume
      accessMode: ReadWriteOnce
      # -- Storage class for logs volume
      storageClass: "default"

  configuration:
    authorization:
      enabled: true
      apiKey:
        key: "X-Api-Key"
        value: <path:industry-core-hub/data/backend#apiKey>
    submodel_dispatcher:
      path: "./data/submodels"
    edc:
      controlplane:
        hostname: "https://edc-provider-ichub-control.int.catena-x.net"
        apikeyheader: "X-Api-Key"
        apikey: <path:industry-core-hub/data/edc-provider#authKey>
        managementpath: "/management"
        protocolPath: "/api/v1/dsp"
        catalogPath: "/catalog"
    # -- Digital Twin Registry configuration
    digitalTwinRegistry:
      hostname: "https://dtr-ichub.int.catena-x.net/"
      apiPath: "/api/v3"
      # -- Set this to the urlPrefix defined in your DTR values. [Default value](https://github.com/eclipse-tractusx/sldt-digital-twin-registry/blob/cc9c63c12d96e48050a1b24eca022277075cf6c7/charts/registry/values.yaml#L86)
      uri: ""
      lookup:
        # -- Same as the uri above
        uri: ""
    # -- Database connection config; database connection settings are inferred from postgresql or externalDatabase sections.
    database:
      echo: true
  ingress:
      enabled: true
      className: "nginx"
      ## Optional annotations when using the nginx ingress class
      annotations:
       cert-manager.io/cluster-issuer: letsencrypt-prod
      #   nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      #   nginx.ingress.kubernetes.io/use-regex: "true"
      #   nginx.ingress.kubernetes.io/enable-cors: "true"
      #   # -- Provide CORS allowed origin.
      #   nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.example.org"
      # -- Ingress TLS configuration
      tls:
       - secretName: "backend-ichub.int.catena-x.net-tls"
         hosts:
           - "backend-ichub.int.catena-x.net" 
        # # -- Provide tls secret.
        # - secretName: ""
        #   # -- Provide host for tls secret.
        #   hosts:
        #     - ""
      hosts:
      - host: "backend-ichub.int.catena-x.net"
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service: "backend"
              port: 8000
